[tools]
go = "1.25.7"

[env]
_.file = { path = ".env" }

[vars]
app = "academy"
cmd = "./cmd/{{vars.app}}"

[tasks.run]
description = "Run the app"
run = "go run {{vars.cmd}}"

[tasks.build]
description = "Build the app"
run = "go build -o bin/{{vars.app}} {{vars.cmd}}"

[tasks.watch]
description = "Run with live reload"
run = "watchexec -r -e go -- go run {{vars.cmd}}"

[tasks.clean]
description = "Remove build artifacts"
run = "rm -rf bin/"

[tasks."migrate:down"]
description = "Down all migrations with dbmate"
run = "dbmate -d './internal/migrations' down"

[tasks."migrate:up"]
description = "Run all migrations with dbmate"
run = "dbmate -d './internal/migrations' up"
